ersion: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zarantem99
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
